### ISSUE TITLE
helloblock.addresses.batchGet returns ENOTFOUND

### ISSUE THREAD

**Issue by thallium205** [helloblock/helloblock-js#1]
When calling batchGet for addresses endpoint, I get:

{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo"}

I checked the REST API and it is working correctly.

**Comment by sidazhang** [comment]
@thallium205 could you please paste a code snippet? I am not unable to reproduce what you have

Below is what I used:

``` js
var helloblock = require('helloblock-js')({network: 'testnet'})
helloblock.addresses.batchGet(['n2un6DEMqC52yD2riMTvAnzsSnjM62Sf8S'], function(err, res, resource) {
        console.log(err, res, resource)
})
```
