### ISSUE TITLE
Error: Insufficient Balanace

### ISSUE THREAD

**Issue by weilu** [helloblock/helloblock-js#3]
```
helloblock.faucet.withdraw(address, 20000, function(err) {
  if(err) return console.log(err) // Error: Insufficient Balanace
})
```

Maybe you testnet faucet is running low?

**Comment by sidazhang** [comment]
@weilu 

Yep Faucet ran out of money. Will refill right now

**Comment by sidazhang** [comment]
@weilu Just put a small amount of bitcoins into it. I am looking for the other keys with more bitcoins.

I was meant to fill this up a few days ago. My bad :(
